### ISSUE TITLE
Basic user quotas

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#248]
- Based on keycloak groups and user attributes

Attributes:
- quota-ws-max: Limits the number of total owned workspaces for the user
- quota-ws-open: Limits the number of total open workspaces for the user
- quota-ws-maxcpu: 
- quota-ws-maxmemory:

Attribute is checked on the logged-in user, then on groups for the user.

**Comment by filippomc** [comment]
quota-ws-storage-max sets the storage for the workspaces.

Use a master JSON/YAML file that defines all the quota keys and default values.

```yaml
# sets the maximum number of workspaces for the user
quota-ws-max: 5
quota-ws-open: 3
quota-ws-maxcpu: 1
quota-ws-maxmemory: 1.5G
quota-ws-storage-max: 1G
```
