### ISSUE TITLE
Test network storage solution

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSBv2#600]
- [x] Add network storage to the cluster and storageclass
- [x] Test new volume provisioning on v2dev

**Comment by zsinnema** [comment]
There are 2 architectures possible for network storage:
1. buckets (object store)
2. nfs (filesystem)

in this issue I will focus on the nfs network storage

gcp offers also a nfs service called Filestore, (see pricing https://cloud.google.com/filestore/pricing, basic $020 / GB / month), the minimum is 1TB, which means a minimum of $200 / month
max. 500 clients concurrent and a maximum of 10 "disks"
imho this is not the path we should walk....

another option is to deploy a NFS server in the cluster and let all deployments use it. I've attached a sample yaml file for creating a cluster global NSF server. You can install it using `kubectl apply -f nfssvr.yaml` . This command will install a sample NFS server in the default namespace with a 5GB disk.

Optional (recommended) after the NFS server is created you should create a storageclass that will use the NFS server. With this storageclass dynamic provisioning of PV(C) will be supported. Creating new PVCs just need to provide the storageclass. The storageclass will connect to the nfs server. I recommend this storageclass (with provisioner): https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
Installation: ```
nfsserverip=$(kubectl -n default get --no-headers=true service|awk '{print $3}')
helm install my-release nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
    --set nfs.server=${nfsserverip} \
    --set nfs.path=/exports
```

**Comment by zsinnema** [comment]
nfssvr.yaml:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-svr-vol
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
        - name: storage
          mountPath: /exports
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: nfs-svr-vol
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
  namespace: default
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: nfs-server
```

**Comment by zsinnema** [comment]
after this we need to change the default storageclass that is used for new workspaces: edit the template.yaml on the workspaces pod and change it to this:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{name}"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{size}"
```
